### ISSUE TITLE
Crash w/ PrimalCore

### ISSUE THREAD

**Issue by WenXin20** [SleeplessDevelopment/Plated#1]
Forge v14.23.4.2747-1.12.2
[PrimalCore](https://minecraft.curseforge.com/projects/primalcore) v0.6.68
Plated v0.1.0
I recieved the following crash after creating a new world.
[Crash Report](https://gist.github.com/WenXin20/580797ddd97f3ef58b10ee0520038076)

**Comment by ChloeDawn** [comment]
This is a bug with PrimalCore, you can report it to their issue tracker [here](https://github.com/An-Sar/PrimalCore/issues).
