### ISSUE TITLE
Possible conflict between Plated and Red Bits

### ISSUE THREAD

**Issue by Li-Liu** [SleeplessDevelopment/Plated#6]
### **Issue Description:**

The world fails to load and Minecraft crashes to desktop when I try to add _Plated_ to an existing world with the mod _Red Bits_ in it.

Removing _Plated_ allows the world to load properly.

### **Step(s) to Reproduce:**

1. Install _Plated_ to a modpack with a world created with _Red Bits_ as one of the mods in the instance.
2. Attempt to load the world after installing _Plated_.

### **Environment:**

- **Minecraft:** v1.16.4
- **Mod Loader:** Fabric 0.10.8
- **Plated:** 2.0.0
- **Red Bits:** 1.6.0

### **Log(s):**

[latest.log](https://github.com/ChloeDawn/Plated/files/5806916/latest.log)
[crash-2021-01-12_22.55.00-client.txt](https://github.com/ChloeDawn/Plated/files/5806920/crash-2021-01-12_22.55.00-client.txt)

### **Screenshot(s):**

N/A

### **Additional Note(s):**

I have not tested by removing _Red Bits_ to see if the issue occurs with other mods as well, I pin-pointed the cause to point to _Plated_ immediately, and I have limited allowed playtime each day.

**Comment by ChloeDawn** [comment]
Pending on https://github.com/magistermaks/mod-redbits/pull/5 which will greatly simplify the requirements of my support.

**Comment by ChloeDawn** [comment]
Fixed in https://github.com/ChloeDawn/Plated/releases/tag/2.0.1
https://www.curseforge.com/minecraft/mc-mods/plated/files/3169580
