### ISSUE TITLE
[Incompatibility] Better End

### ISSUE THREAD

**Issue by saltyseadoggo** [SleeplessDevelopment/Plated#7]
Pressure plates added by [Better End](https://github.com/paulevsGitch/BetterEnd) do not visibly orient correctly when placed on walls or ceilings, even though their black outline, collision and redstone connectivity do.

Of note, a similar mod that dynamically adds vertical slabs, [Better Slabs](https://github.com/Eilux/BetterSlabs), has similar issues, with Better End slabs not orienting vertically. I would suspect that Better End is doing something strange here, but its dev, paulevs, insists that it was on Better Slabs' side. It may be worth getting in touch with them or looking at their implementation to find what could be causing dynamic model generation based on its assets to fail. If you can find out what, it could help that issue as well. I could also pester paulevs again if you'd like. [Here's the aforementioned issue.](https://github.com/paulevsGitch/BetterEnd/issues/47)

**Attachments**
![2021-01-13_11 06 22](https://user-images.githubusercontent.com/69029346/104497971-fab85200-558f-11eb-80c2-4925c0adddc3.png)

**Comment by ChloeDawn** [comment]
Do you have any other mods loaded? Neither me nor Better End could cause this from what I can tell at a glance

**Comment by saltyseadoggo** [comment]
I just tested it again with only Plated 2.0.0, Better End 0.8.7, and Fabric API 0.29.3, and the issue is still present.

**Comment by ChloeDawn** [comment]
This appears to be because BetterEnd injects their static models at runtime rather than using a model API or just generating the JSONs for the JAR file. Since they do not provide block state definitions to the model loader I cannot support it easily.

**Comment by saltyseadoggo** [comment]
Thank you for taking the time to make a tech analysis, and thank you for letting paulevs know! Hopefully we can get this resolved on their end.~

**Comment by paulevsGitch** [comment]
This will be [fixed](https://github.com/paulevsGitch/BetterEnd/issues/47#issuecomment-767610849) in the next BetterEnd version

**Comment by paulevsGitch** [comment]
Fixed in BetterEnd 0.9.0
