### ISSUE TITLE
Pressure Plates do not Break on Extended Pistons

### ISSUE THREAD

**Issue by milkev** [SleeplessDevelopment/Plated#8]
when a piston extends, blocks placed on its sides such as torches or levers are broken, however the pressure plates are not, despite following the same physics as torchs and levers in all other situations.
![2021-01-20_04 34 10](https://user-images.githubusercontent.com/22010128/105169532-e5d04700-5ad8-11eb-8a30-46874aab56ba.png)

**Comment by ChloeDawn** [comment]
This is reproducible in vanilla (this mod not present), it is intended behavior.
